### ISSUE TITLE
Appimage crash on start: GPU process isn't usable

### ISSUE THREAD

**Issue by Flashwalker** [picturama/picturama#116]
```
$ firejail --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage ./Picturama-1.3.1.AppImage
Parent pid 2017011, child pid 2017013

** Warning: dropping all Linux capabilities and setting NO_NEW_PRIVS prctl **

Mounting appimage type 2
Child process initialized in 35.55 ms
[2:1122/111149.911780:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.

Parent is shutting down, bye...
AppImage detached
```

**Comment by til-schneider** [comment]
Picturama needs access to the GPU (hardware accelerated graphics) in order to function. You either have a graphic card which has no GPU support or `firejail` blocks access to it.

**Comment by Flashwalker** [comment]
> Picturama needs access to the GPU (hardware accelerated graphics) in order to function. You either have a graphic card which has no GPU support or `firejail` blocks access to it.

Noup.
This issue occurs independently of firejail, i tested, and i have nvidia driver with the oficial driver.
Actually this problem happens with some appimages.  
I (and other people) had the same issue e.g. with [Motrix](https://github.com/agalwood/Motrix) appimage. But i don't have it now, so looks like they fixed it.

**Comment by Flashwalker** [comment]
It is Electron issue, when Electron-libs don't match your system

`--in-process-gpu` option helps as workaround.
Also `--disable-gpu-sandbox` or `--no-sandbox` helps too

**Comment by til-schneider** [comment]
Interesting. Can you share the full command which worked in the end for you?

**Comment by Flashwalker** [comment]
These all works for me (regardless via firejail or not):
```
firejail --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage /home/user/Downloads/Picturama-1.3.1.AppImage --in-process-gpu

firejail --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage /home/user/Downloads/Picturama-1.3.1.AppImage --disable-gpu-sandbox

firejail --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage /home/user/Downloads/Picturama-1.3.1.AppImage --no-sandbox
```

I found on internet this issue affects different Electron based apps
