### ISSUE TITLE
Can not start the app - linux platform

### ISSUE THREAD

**Issue by vnnv** [picturama/picturama#28]
There is an error while starting the app in linux. 

Please rename test-ui/core/UITester.less to UiTester. This will resolve the problem on case sensitive systems.

**Comment by til-schneider** [comment]
I tested the AppImage download on Ubuntu and it works fine. Further more I'm developing on a Mac which has a case sensitive file system, too.

Please give me more information about your error: Which Linux distribution are you using? How did you start Picturama (did you use the AppImage or something else)? Can you post the original error message?

**Comment by vnnv** [comment]
Hello. Here  are some details:
Linux - Arch Linux 
Clone the repo
Start `yarn` and `yarn start`

The result is:
  Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/less-loader/dist/cjs.js!src/test-ui/entry.less:
        Entrypoint mini-css-extract-plugin = *
        [./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js!./src/test-ui/entry.less] 319 bytes {mini-css-extract-plugin} [built] [failed] [1 error]
        
        ERROR in ./src/test-ui/entry.less (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js!./src/test-ui/entry.less)
        Module build failed (from ./node_modules/less-loader/dist/cjs.js):
        
        
        @import "./core/UiTester.less";
        ^
        Can't resolve './core/UiTester.less' in '/mnt/devel/projects/github/test/picturama/src/test-ui'
              in /mnt/devel/projects/github/test/picturama/src/test-ui/entry.less (line 1, column 0)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
-----
Check this directory - picturama/src/test-ui/core/
There are two files: ` UITester.less` and `UiTester.tsx`
In `UiTester.tsx` you try to import ` import './UiTester.less'`

But the file is UI - with capital `I` letter instead of `i`

**Comment by til-schneider** [comment]
Thank you for the details. I fixed the casing with f9efe8d451302313f9459d34de8820e68403340b.
