### ISSUE TITLE
Support High Resolution displays when viewing photos

### ISSUE THREAD

**Issue by cxcxcxcx** [picturama/picturama#31]
Hello,
I noticed that the image quality is significantly worse compared to the default system viewer. Here is an example in Mac.

Is it a known problem?

<img width="563" alt="截屏2020-02-12下午10 52 23 1" src="https://user-images.githubusercontent.com/236044/74409006-ad18ef80-4dea-11ea-923b-5a31ddef663b.png">

**Comment by til-schneider** [comment]
Your system viewer applies a sharpen effect on your photo. And the colors are a little bit more saturated as well.

If you look into detail, you can see dark borders at edges with high contrast which probably don't exist in the original image:
![image](https://user-images.githubusercontent.com/3951508/74416050-cd759800-4e44-11ea-8968-cd72d65f945f.png)

So the display of the system viewer might look nicer, but it's a pimped display which is actually not accurate. Picturama just scales the image without applying any effects.

But I'll keep this in mind. Maybe I could add an option for this. It depends whether you prefer a neutral display (if you want to judge your photos) or if you just want to view your photos (and don't care if they have additional effects applied).

**Comment by cxcxcxcx** [comment]
I tried a different operating system and a different monitor, the problem
stays. HiDpi is on so that maybe a reason. But even if I double the size of
the canvas the problem stays.

I can provide more examples. I think scaling without WebGL would probably
even give a different result. Will update the issue.

Til Schneider <notifications@github.com> 于 2020年2月13日周四 00:41写道：

**Comment by LeonardoGentile** [comment]
Hello,
When this project started there was a Telegram group. 
At the time I brought up a concern: given that the underlying electron framework is just a browser I had a recall that in any browsers the rendering of images are limited to a certain amount of dpi. I might be wrong or it might be a thing of the past but I couldn't get an answer to this concern.

So maybe try to dig in this direction?

**Comment by cxcxcxcx** [comment]
That might be a different issue. I'm worried about the WebGL thing.

2 pieces of evidence that it's not the system viewer's special effect:
1. I opened the photo in my Chrome, and this is the html I made:
<img src="./IMG_20200123_120657.jpg" width=800 height=600/>
As you can see, the photo looks sharp and clear. The right-most image is Chrome.
2. I opened the screenshot in the system image viewer, the screenshot is not "sharpened" (the left-most image/the blurry one) 

<img width="759" alt="截屏2020-02-13下午9 02 10" src="https://user-images.githubusercontent.com/236044/74503097-b49ccf00-4ea4-11ea-978e-c301fb8bef49.png">

re the HiDPI problem, the canvas needs to be sized by the CSS pixels * window. devicePixelRatio . This is not done in the current code. I tried to change the canvas size and viewport of Picturama, but it didn't solve the problem. Reference:
https://webglfundamentals.org/webgl/lessons/webgl-resizing-the-canvas.html

Next, I can test on an old screen without HiDPI, will let you know if it appears HiDPI related.

**Comment by cxcxcxcx** [comment]
Tested on an old 1080p monitor. Seems that we are both right, partially.

This is a screenshot from the 1080p monitor:
![截屏2020-02-13下午9 25 26](https://user-images.githubusercontent.com/236044/74504043-ce8be100-4ea7-11ea-8149-897f4d48c2da.png)

This is from Mac internal display:
<img width="494" alt="截屏2020-02-13下午9 26 36" src="https://user-images.githubusercontent.com/236044/74504073-e06d8400-4ea7-11ea-9c19-7f0e64224a46.png">

The ordering are both: browser, Picturama, Mac Preview

From the top image, I'd agree that Mac Preview is probably doing something special. But Picturama looks similar to the browser one, which isn't bad.

The bottom image, however, shows that Picturama is significantly worse, on an HiDPI display.

This is probably caused by the canvas size issue. What do you think?

**Comment by cxcxcxcx** [comment]
Yay, after increasing the canvas size, I was able to fix it locally. However, it breaks the cropping tool. If I don't have the final fix, I will send whatever I have.

**Comment by til-schneider** [comment]
Yes, I can confirm this. The photos in the detail view are shown in a WebGL-canvas which doesn't use the full resolution if you happen to have a HiDPI/Retina-Display.

Sorry, I didn't realize that you had a HiRes display. And I assumed that the sharpening effect wasn't already applied to the original image.

**Comment by til-schneider** [comment]
I just added support for HiRes displays. See 3215c1ab9a79362c39bc6d612d9285cffeece10a.
