### ISSUE TITLE
Automatic Tagging

### ISSUE THREAD

**Issue by bismay4u** [picturama/picturama#35]
While scanning a the photos, it often becomes tedious to tag them independently. Year wise organising helps but still photos need to have some tag.

My Suggestion, normally we all put photos in named folders, so if we can add the photo directory name as tags it will reduce the work of tagging photos manually.

Thanks

**Comment by til-schneider** [comment]
Yes, viewing photos by folder is a nice thing. But my plans are to add an own view for this purpose (rather than mixing this up with tags).

These are the views I have planned in the long run:
- Folders
- Map
- Persons
- Albums
- Imports

**Comment by Amar0ks** [comment]
> These are the views I have planned in the long run:
>    Folders
>    Map
>   Persons
>  Albums
>  Imports

I would also appreciate a grouping per week or month.

**Comment by til-schneider** [comment]
I'm closing this one, since this use case will be addressed in another way (not using automatic tagging).

**Comment by til-schneider** [comment]
> I would also appreciate a grouping per week or month.

This is discussed in #48.
