### ISSUE TITLE
Add hide menubar in settings

### ISSUE THREAD

**Issue by aelisya** [picturama/picturama#51]
Is there a possibility to add hide a menu bar in the settings because on windows its very ugly to see that

<img src="https://media.discordapp.net/attachments/759213582415298580/759213605538758656/unknown.png">

Thanks in advance

**Comment by til-schneider** [comment]
I removed the menu completely on Windows and Linux. So all platforms now have a compact title bar.

@aelisya: Could you [add the french localization](https://github.com/picturama/picturama/edit/master/src/common/i18n/text_fr.ts) for the MacOS menu?

**Comment by aelisya** [comment]
@til-schneider yes il will do that today :)

**Comment by til-schneider** [comment]
I just released version 1.3.0 with the compact title bar.

**Comment by til-schneider** [comment]
Windows needed a bugfix. So it's version 1.3.1 for Windows now.
