### ISSUE TITLE
node-libheif and libraw not supported 

### ISSUE THREAD

**Issue by akjoshi** [picturama/picturama#68]
Windows 10.

$yarn start
...
node-libheif is not supported Error: Cannot find module 'node-libheif'
libraw is not supported Error: Cannot find module 'libraw'
...

**Comment by til-schneider** [comment]
These dependencies are optional. They don't build on Windows.
For `node-libheif`, Picturama uses `heic2any` instead (which is 3 times slower though).
The lacking Windows build of `libraw` is already addressed by #25.
