### ISSUE TITLE
regression: EXIF orientation is not handled properly

### ISSUE THREAD

**Issue by tuomassalo** [picturama/picturama#69]
**What I did:** I downloaded some sample images with EXIF orientation data, from https://github.com/recurser/exif-orientation-examples.

**What happened:** the orientation data was not read properly, resulting in distorted images in both master and detail view. All the thumbnails should look the same (apart from text). See image.

**What I expected:** orientation data was handled transparently, i.e. so that all images look as they look in e.g. macos Finder.

NB: The problem happens with the current `master` version, but not with a version from lasty October. I did a fresh clone, so it shouldn't be about e.g. outdated submodules.

![Screenshot 2021-01-22 at 14 25 56](https://user-images.githubusercontent.com/189964/105491342-d0b50d00-5cbe-11eb-8dd9-a10e9d7a667c.png)

**Comment by til-schneider** [comment]
I changed to another EXIF parsing library. Maybe this caused the regression.

**Comment by til-schneider** [comment]
Thank you for the EXIF orientation examples repo, by the way. I added those to the tests.
