### ISSUE TITLE
Support multi-select using shift-key

### ISSUE THREAD

**Issue by akjoshi** [picturama/picturama#70]
At the moment, the only way to select multiple files is to hold ctrl-key and keep selecting images one by one. 
Enable multi-select using shift-key that behaves like any file explorer. - holding a shift-key and pressing any two images will select all images between and including those two images.

use cases:
1. select a group of files for deletion
2. select a group of files for fav

**Comment by til-schneider** [comment]
I'm already addressing this in #64. Actually, this will be part of the next release.
